version: '3'

services:
  pg:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  # go:
  #   build:
  #     dockerfile: Dockerfile
  #     context: app/
  #   ports:
  #     - 8080:8080

volumes:
  db_data:
    driver: local
